function ok = sf_verify_octave(varargin)
%SF_VERIFY_OCTAVE  Check that SeaFreeze reproduces MATLAB results under Octave.
%
%   ok = sf_verify_octave()
%   ok = sf_verify_octave('rtol', 1e-8, 'verbose', true, 'sections', {'getprop'})
%
%   This is a portability check, not a port of the MATLAB test suite (which
%   uses matlab.unittest and does not run under Octave).  It leans on the two
%   reference files in test/ that were generated by MATLAB and happen to be
%   saved in MAT v7, so Octave can read them directly:
%
%     test/reference_getProp.mat     13 cases (incl. water_Brown2026 and (rho,T)), every property
%     test/reference_phaselines.mat  18 equilibrium curves
%
%   Those give genuine MATLAB ground truth to compare against, so a green run
%   here means the Octave results agree numerically with MATLAB and not merely
%   that nothing threw an error.
%
%   Options (name/value):
%     'rtol'     relative tolerance for property comparison (default 1e-10)
%     'atol'     absolute floor, for values near zero      (default 1e-12)
%     'sections' cell array from {'getprop','phaselines','smoke'}
%                (default: all three)
%     'dT'       T-grid step for the phase-line section.  Default [] reuses
%                each reference case's own dT, reproducing its grid exactly.
%                Pass a larger value (e.g. 0.05) for a much faster, coarser run.
%     'verbose'  print per-field detail on failures (default true)
%
%   Returns true when every selected section passes.
%
%   Usage from a shell:
%     octave --no-gui --eval "addpath(genpath('Matlab')); sf_verify_octave"
%
%   See also: SF_getprop, SF_PhaseLines, sf_is_octave

opt = parse_opts(varargin);

here = fileparts(mfilename('fullpath'));
addpath(genpath(here));

fprintf('\nSeaFreeze portability check\n');
fprintf('  interpreter : %s\n', interpreter_name());
fprintf('  version     : %s\n', SeaFreeze_version());
fprintf('  rtol/atol   : %g / %g\n\n', opt.rtol, opt.atol);

ok = true;
if any(strcmp(opt.sections, 'getprop'))
    ok = check_getprop(here, opt) && ok;
end
if any(strcmp(opt.sections, 'phaselines'))
    ok = check_phaselines(here, opt) && ok;
end
if any(strcmp(opt.sections, 'smoke'))
    ok = check_smoke(opt) && ok;
end

fprintf('\n=============================\n');
if ok
    fprintf('ALL CHECKS PASSED\n');
else
    fprintf('SOME CHECKS FAILED\n');
end
fprintf('=============================\n\n');

if nargout == 0
    clear ok
end
end


% ======================================================================
%  Section 1 — property parity against MATLAB-generated reference values
% ======================================================================

function ok = check_getprop(here, opt)
fprintf('--- SF_getprop vs test/reference_getProp.mat ---\n');
ok = true;

ref_file = fullfile(here, 'test', 'reference_getProp.mat');
if exist(ref_file, 'file') ~= 2
    fprintf('  SKIP: %s not found\n\n', ref_file);
    return
end
R = load(ref_file);

cases = fieldnames(R);
for c = 1:numel(cases)
    name = cases{c};
    ref  = R.(name);

    PT       = rebuild_PT(ref);
    material = ref.input_material;

    t0  = tic;
    if isfield(ref, 'input_mode') && strcmp(ref.input_mode, 'rhoT')
        got = SF_getprop(PT, material, [], 'input', 'rhoT');   % (rho,T) cases (1.2)
    else
        got = SF_getprop(PT, material);
    end
    dt  = toc(t0);

    % Compare every field the reference carries except the recorded inputs.
    fields = setdiff(fieldnames(ref), ...
        {'input_P','input_T','input_m','input_type','input_material','input_mode'});

    worst = 0; worst_field = ''; nbad = 0; missing = {};
    for f = 1:numel(fields)
        fn = fields{f};
        if ~isfield(got, fn)
            missing{end+1} = fn; %#ok<AGROW>
            continue
        end
        [pass, dev] = compare_arrays(got.(fn), ref.(fn), opt.rtol, opt.atol);
        if dev > worst, worst = dev; worst_field = fn; end
        if ~pass
            nbad = nbad + 1;
            if opt.verbose
                fprintf('      %-16s worst rel dev %.3g\n', fn, dev);
            end
        end
    end

    if isempty(missing) && nbad == 0
        fprintf('  PASS  %-24s %2d fields, worst %-8.2g (%s)  [%.2fs]\n', ...
                name, numel(fields), worst, worst_field, dt);
    else
        ok = false;
        fprintf('  FAIL  %-24s %d field(s) over tolerance', name, nbad);
        if ~isempty(missing)
            fprintf(', %d missing: %s', numel(missing), strjoin(missing, ','));
        end
        fprintf('  (worst %.3g in %s)\n', worst, worst_field);
    end
end
fprintf('\n');
end


function PT = rebuild_PT(ref)
% Reconstruct the SF_getprop input from the inputs the reference recorded.
P = double(ref.input_P(:));
T = double(ref.input_T(:));
m = double(ref.input_m(:));
has_m = ~isempty(m) && ~all(isnan(m));

if strcmp(ref.input_type, 'grid')
    if has_m
        PT = {P.', T.', m.'};
    else
        PT = {P.', T.'};
    end
else
    if has_m
        if isscalar(m), m = repmat(m, numel(P), 1); end
        PT = [P, T, m];
    else
        PT = [P, T];
    end
end
end


% ======================================================================
%  Section 2 — equilibrium curves against the MATLAB reference
% ======================================================================

function ok = check_phaselines(here, opt)
fprintf('--- SF_PhaseLines vs test/reference_phaselines.mat ---\n');
ok = true;

ref_file = fullfile(here, 'test', 'reference_phaselines.mat');
if exist(ref_file, 'file') ~= 2
    fprintf('  SKIP: %s not found\n\n', ref_file);
    return
end
R = load(ref_file);

% Curves are compared geometrically rather than point-by-point: Octave's
% contourc may order or split a contour differently from MATLAB's, so a
% mismatched point count is not by itself an error. What must hold is that the
% two curves lie on top of each other.
TOL_DIST = 0.05;   % max nearest-neighbour distance, in sqrt(MPa^2 + K^2)

cases = fieldnames(R);
for c = 1:numel(cases)
    name = cases{c};
    ref  = R.(name);

    rA = SF_phase_range(ref.matA);
    rB = SF_phase_range(ref.matB);
    T_lo = max([rA.T(1), rB.T(1), 1.0]);
    T_hi = min(rA.T(2), rB.T(2));
    if isempty(opt.dT), dT = ref.dT; else, dT = opt.dT; end
    T_grid = T_lo:dT:T_hi;

    t0 = tic;
    try
        if isnan(ref.m)
            got = SF_PhaseLines(ref.matA, ref.matB, 'T', T_grid, 'segment', 'all');
        else
            got = SF_PhaseLines(ref.matA, ref.matB, 'm', ref.m, ...
                                'T', T_grid, 'segment', 'all');
        end
    catch err
        ok = false;
        fprintf('  FAIL  %-24s errored: %s\n', name, err.message);
        continue
    end
    dt = toc(t0);

    d = curve_distance(got.P(:), got.T(:), ref.P(:), ref.T(:));
    npts_ref = numel(ref.P);
    npts_got = numel(got.P);

    if d <= TOL_DIST
        fprintf('  PASS  %-24s max dist %-8.3g  (%d vs %d pts)  [%.2fs]\n', ...
                name, d, npts_got, npts_ref, dt);
    else
        ok = false;
        fprintf('  FAIL  %-24s max dist %.3g exceeds %g  (%d vs %d pts)\n', ...
                name, d, TOL_DIST, npts_got, npts_ref);
    end
end
fprintf('\n');
end


function d = curve_distance(P1, T1, P2, T2)
% Symmetric max nearest-neighbour distance between two (P,T) curves,
% in sqrt(MPa^2 + K^2).
%
% Only the *query* side is subsampled, never the side being searched. Thinning
% the target set would inflate the distance by roughly half its own point
% spacing even for two identical curves, which on a 54 000-point reference
% curve swamps the difference actually being measured.
MAX_QUERY = 3000;
[f1, g1] = finite_pts(P1, T1);
[f2, g2] = finite_pts(P2, T2);
if isempty(f1) || isempty(f2)
    d = Inf;
    return
end
[q1, r1] = subsample(f1, g1, MAX_QUERY);
[q2, r2] = subsample(f2, g2, MAX_QUERY);
d = max(one_way(q1, r1, f2, g2), one_way(q2, r2, f1, g1));
end


function [P, T] = finite_pts(P, T)
keep = isfinite(P) & isfinite(T);
P = P(keep); T = T(keep);
end


function [P, T] = subsample(P, T, n)
if numel(P) > n
    idx = round(linspace(1, numel(P), n));
    P = P(idx); T = T(idx);
end
end


function d = one_way(Pa, Ta, Pb, Tb)
% max over points of a of the distance to the nearest point of b.
d = 0;
for i = 1:numel(Pa)
    dist = min(sqrt((Pb - Pa(i)).^2 + (Tb - Ta(i)).^2));
    if dist > d, d = dist; end
end
end


% ======================================================================
%  Section 3 — smoke tests over the rest of the public API
% ======================================================================

function ok = check_smoke(opt) %#ok<INUSD>
fprintf('--- Smoke tests ---\n');
ok = true;
defs = sf_material_defs();

% ---- every material, grid and scatter, all properties -------------------
for k = 1:numel(defs.known_materials)
    mat = defs.known_materials{k};
    is_nacl = ismember(mat, defs.nacl_materials);
    % Probe each material where its EOS is meant to be used. The liquid
    % parametrizations get a warmer, lower-pressure box: water_Brown2018 (Brown 2018)
    % is fitted for high pressure and its cold high-P corner -- 250 K above
    % ~1400 MPa, which is deep inside the ice VI/VII field -- returns negative
    % specific volume. That is a property of the shipped spline, not of the
    % Octave port, so probing it here would be testing the wrong thing.
    if ismember(mat, defs.liquid_phases)
        Pwin = [1 400];  Twin = [275 350];
    else
        Pwin = [1 1500]; Twin = [250 300];
    end
    try
        r = SF_phase_range(mat);
        P = interior(r.P, 3, Pwin);
        T = interior(r.T, 3, Twin);
        if is_nacl
            m = interior(r.m, 2, [0.1 5]);
            g = SF_getprop({P, T, m}, mat);
            s = SF_getprop([P(:), T(:), repmat(m(1), 3, 1)], mat);
            want_sz = [numel(P) numel(T) numel(m)];
        else
            g = SF_getprop({P, T}, mat);
            s = SF_getprop([P(:), T(:)], mat);
            want_sz = [numel(P) numel(T)];
        end
        assert_true(isequal(size(g.rho), want_sz), ...
                    sprintf('%s: grid rho size %s, expected %s', ...
                            mat, mat2str(size(g.rho)), mat2str(want_sz)));
        assert_true(numel(s.rho) == 3, sprintf('%s: scatter rho should be 3 long', mat));
        assert_true(all(isfinite(g.rho(:))), sprintf('%s: non-finite rho on grid', mat));
        assert_true(all(g.rho(:) > 0), sprintf('%s: non-positive density', mat));
        fprintf('  PASS  %-18s grid %-14s scatter ok  (%d fields)\n', ...
                mat, mat2str(size(g.rho)), numel(fieldnames(g)));
    catch err
        ok = false;
        fprintf('  FAIL  %-18s %s\n', mat, err.message);
    end
end

% ---- selective props ----------------------------------------------------
ok = run_check('props selection', @() check_props(), ok);

% ---- SF_WhichPhase ------------------------------------------------------
ok = run_check('SF_WhichPhase pure',  @() check_whichphase_pure(),  ok);
ok = run_check('SF_WhichPhase NaCl',  @() check_whichphase_nacl(),  ok);

% ---- SF_rho2P round trip ------------------------------------------------
ok = run_check('SF_rho2P round trip', @() check_rho2p(), ok);

% ---- SF_WPD renders -----------------------------------------------------
ok = run_check('SF_WPD renders',      @() check_wpd(),  ok);
ok = run_check('SF_WPD NaCl overlay', @() check_wpd_nacl(), ok);

% ---- constructs whose Octave support needed confirming ------------------
ok = run_check('deprecated alias',    @() check_alias(),      ok);
ok = run_check('deprecated F prop',   @() check_f_alias(),    ok);
ok = run_check('input validation',    @() check_errors(),     ok);
ok = run_check('phase lines multi-m', @() check_phaselines_multi(), ok);

fprintf('\n');
end


function check_wpd_nacl()
% Exercises the NaClaq overlay: parula(), legend(ax,...) and the struct-array
% plotting path, none of which the pure-water figure touches.
old = get(0, 'defaultfigurevisible');
set(0, 'defaultfigurevisible', 'off');
cleanup = onCleanup(@() set(0, 'defaultfigurevisible', old)); %#ok<NASGU>
fig = SF_WPD('solute', 'NaCl', 'm', [0.5 2], 'meta', 'none', 'labels', false);
assert_true(sf_ishandle_type(fig, 'figure'), 'SF_WPD NaCl did not return a figure');
close(fig);
end


function check_alias()
% The deprecated SeaFreeze() wrapper must still forward to SF_getprop.
% Its one-shot warning uses a persistent, so do not assert the warning fires:
% it may already have been consumed earlier in the session.
old_state = warning('off', 'SeaFreeze:deprecated');
cleanup = onCleanup(@() warning(old_state)); %#ok<NASGU>
a = SeaFreeze([900 255], 'VI', 'rho');
b = SF_getprop([900 255], 'VI', 'rho');
assert_true(a.rho == b.rho, 'SeaFreeze() alias disagrees with SF_getprop');
end


function check_f_alias()
% 'F' is a deprecated alias for 'A'. This is the only path through the hoisted
% `persistent warned_F` and through union/setdiff with the 'stable' option.
old_state = warning('off', 'SeaFreeze:deprecatedProperty');
cleanup = onCleanup(@() warning(old_state)); %#ok<NASGU>
out = SF_getprop([900 255], 'VI', {'F'});
assert_true(isfield(out, 'F'), 'requesting F did not return an F field');
assert_true(~isfield(out, 'A'), 'requesting only F should not also return A');
ref = SF_getprop([900 255], 'VI', {'A'});
assert_true(out.F == ref.A, 'F does not equal A');
end


function check_errors()
% The documented error identifiers must survive on Octave.
expect_error(@() SF_getprop([900 255], 'nosuchphase'),  'SeaFreeze:unknownMaterial');
expect_error(@() SF_getprop([900 255], 'VI', 'nope'),   'SeaFreeze:unknownProperty');
expect_error(@() SF_getprop([900 255 1], 'VI'),         'SeaFreeze:badInput');
expect_error(@() SF_getprop([900 255], 'NaClaq_Brown2026'),       'SeaFreeze:badInput');
expect_error(@() SF_phase_range('nosuchphase'),         'SeaFreeze:unknownMaterial');
expect_error(@() sf_load_spline('nosuchphase'),         'sf_load_spline:unknown');
expect_error(@() SF_PhaseLines('Ih', 'VI'),             'SeaFreeze:unsupportedPair');
expect_error(@() SF_PhaseLines('Ih', 'NaClaq_Brown2026'),         'SeaFreeze:badInput');
end


function check_phaselines_multi()
% Several molalities at once returns a struct array, which drives a different
% branch of render_plot (colours from lines(), a hand-built legend).
T = 250:0.5:273;
out = SF_PhaseLines('Ih', 'NaClaq_Brown2026', 'm', [0.5 2], 'T', T, 'segment', 'all');
assert_true(numel(out) == 2, sprintf('expected 2 curves, got %d', numel(out)));
% Render them too: the struct-array branch of render_plot is the only caller of
% lines() and of the hand-assembled legend.
old_vis = get(0, 'defaultfigurevisible');
set(0, 'defaultfigurevisible', 'off');
cleanup = onCleanup(@() set(0, 'defaultfigurevisible', old_vis)); %#ok<NASGU>
plotted = SF_PhaseLines('Ih', 'NaClaq_Brown2026', 'm', [0.5 2], 'T', T, 'plot', true);
assert_true(sf_ishandle_type(plotted(1).fig, 'figure'), ...
            'SF_PhaseLines plot path did not return a figure');
close(plotted(1).fig);
assert_true(~isempty(out(1).P) && ~isempty(out(2).P), 'a curve came back empty');
% More salt depresses the melting point further, so the 2 mol/kg curve must sit
% below the 0.5 mol/kg one at comparable pressure.
assert_true(mean(out(2).T) < mean(out(1).T), ...
            'higher molality should give a lower melting temperature');
end


function expect_error(fn, wanted_id)
threw = false;
try
    fn();
catch err
    threw = true;
    assert_true(strcmp(err.identifier, wanted_id), ...
        sprintf('expected %s, got %s', wanted_id, err.identifier));
end
assert_true(threw, sprintf('expected %s, but no error was raised', wanted_id));
end


function check_props()
out = SF_getprop([900 255], 'VI', {'rho','Cp'});
fn = sort(fieldnames(out));
assert_true(isequal(fn(:).', {'Cp','rho'}), ...
            ['props selection returned ' strjoin(fn(:).', ',')]);
out = SF_getprop([900 255], 'VI', {'Vs'});
assert_true(isequal(fieldnames(out), {'Vs'}), ...
            'requesting Vs should not leak the internal rho/Ks');
end


function check_whichphase_pure()
ph = SF_WhichPhase([0.1 300; 100 250; 900 255]);
assert_true(isequal(ph(:).', [0 1 6]), ...
            ['expected [0 1 6], got ' mat2str(ph(:).')]);
grid_ph = SF_WhichPhase({0:200:1000, 240:20:300});
assert_true(isequal(size(grid_ph), [6 4]), ...
            ['grid shape ' mat2str(size(grid_ph))]);
end


function check_whichphase_nacl()
% Salt depresses the freezing point: at 0.1 MPa and 272 K pure water is ice Ih,
% but a 2 mol/kg NaCl solution is still liquid.
pure = SF_WhichPhase([0.1 272]);
salt = SF_WhichPhase([0.1 272 2.0], 'solute', 'NaCl');
assert_true(pure == 1, sprintf('pure water at 272 K should be ice Ih, got %g', pure));
assert_true(salt == 0, sprintf('2 mol/kg NaCl at 272 K should be liquid, got %g', salt));
end


function check_rho2p()
P_in  = [200; 500; 900];
T_in  = [280; 300; 320];
rho   = SF_getprop([P_in T_in], 'water_Bollengier2019', 'rho');
P_out = SF_rho2P(rho.rho, T_in, 'water_Bollengier2019');
err   = max(abs(P_out(:) - P_in));
assert_true(err < 0.05, sprintf('round-trip error %.3g MPa exceeds 0.05', err));
end


function check_wpd()
old = get(0, 'defaultfigurevisible');
set(0, 'defaultfigurevisible', 'off');
cleanup = onCleanup(@() set(0, 'defaultfigurevisible', old));
fig = SF_WPD('meta', false, 'labels', true);
assert_true(sf_ishandle_type(fig, 'figure'), 'SF_WPD did not return a figure handle');
png = fullfile(tempdir, 'sf_verify_octave_wpd.png');
print(fig, '-dpng', png);
close(fig);
assert_true(exist(png, 'file') == 2, 'SF_WPD figure did not save to PNG');
delete(png);
end


% ======================================================================
%  Helpers
% ======================================================================

function opt = parse_opts(args)
% Hand-rolled rather than inputParser: this script has to survive on an
% interpreter whose inputParser is one of the things being exercised.
opt.rtol     = 1e-10;
opt.atol     = 1e-12;
opt.verbose  = true;
opt.dT       = [];
opt.sections = {'getprop', 'phaselines', 'smoke'};
for k = 1:2:numel(args)
    if k + 1 > numel(args)
        error('sf_verify_octave:badInput', 'Options must come in name/value pairs.');
    end
    name = lower(char(args{k}));
    val  = args{k + 1};
    switch name
        case 'rtol',     opt.rtol = val;
        case 'atol',     opt.atol = val;
        case 'verbose',  opt.verbose = logical(val);
        case 'dt',       opt.dT = val;
        case 'sections', opt.sections = cellstr(val);
        otherwise
            error('sf_verify_octave:badInput', 'Unknown option ''%s''.', name);
    end
end
end


function name = interpreter_name()
if sf_is_octave()
    name = ['GNU Octave ' version()];
else
    name = ['MATLAB ' version()];
end
end


function [pass, worst] = compare_arrays(a, b, rtol, atol)
% Elementwise a ~= b within rtol/atol.  NaN matches NaN; a NaN on one side
% only is a failure.  worst is the largest relative deviation seen.
a = double(a(:));
b = double(b(:));
if numel(a) ~= numel(b)
    pass = false; worst = Inf;
    return
end
nan_a = isnan(a);  nan_b = isnan(b);
if any(nan_a ~= nan_b)
    pass = false; worst = Inf;
    return
end
both = ~nan_a;
if ~any(both)
    pass = true; worst = 0;
    return
end
d     = abs(a(both) - b(both));
scale = max(abs(b(both)), atol);
rel   = d ./ scale;
worst = max(rel);
pass  = all(d <= atol + rtol * abs(b(both)));
end


function v = interior(range, n, want)
% n probe points inside a material's [lo hi] domain.
%
% `want` is a preferred physically meaningful window, clipped to the domain.
% Sampling the raw knot domain is not good enough: a knot range can extend far
% past where the fit means anything (water_IAPWS95 is knotted out to 300 GPa
% and 20 000 K, and its specific volume goes negative in the extreme corner),
% so a fixed fraction of the span would probe nonsense. Where the preferred
% window does not overlap the domain at all -- ice VII/X starts at 1700 MPa --
% fall back to the middle of the domain rather than its edges.
lo = range(1); hi = range(2);
a  = max(lo, want(1));
b  = min(hi, want(2));
if ~(b > a)
    span = hi - lo;
    a = lo + 0.40 * span;
    b = lo + 0.60 * span;
end
pad = 0.02 * (b - a);            % stay off the knot boundaries themselves
v   = linspace(a + pad, b - pad, n);
end


function assert_true(cond, msg)
if ~cond
    error('sf_verify_octave:failed', '%s', msg);
end
end


function ok = run_check(label, fn, ok)
try
    fn();
    fprintf('  PASS  %s\n', label);
catch err
    ok = false;
    fprintf('  FAIL  %-18s %s\n', label, err.message);
end
end
