#!/bin/bash

# Run this script from the Python directory to create PyPI package for upload
# Then, provide __token__ as username and upload key with: python -m twine upload dist/* --verbose

# delete contents of dist folder
if [ -d dist ]; then
  rm -r dist
fi

# copy LICENSE locally
if [ -e LICENSE.txt ]; then
  DELL=0
else
  DELL=1
  cp ../LICENSE.txt .
fi

# update tools then create src and wheel distributions
python3 -m pip install --user --upgrade pip
python3 -m pip install --user --upgrade setuptools wheel build
python3 -m build

# remove local license if copied just for the build
if [ $DELL -eq 1 ]; then
  rm LICENSE.txt
fi
