"""Cross-validation: Python getProp vs MATLAB SF_getprop.

Loads Matlab/test/reference_getProp.mat (generated by
Matlab/test/gen_getProp_reference.m) and calls getProp with identical
inputs. Every numeric property that Matlab returned is compared against
the Python result.

Run from Python/ directory:
    python -m pytest seafreeze/test/test_getProp_vs_matlab.py -v

Tolerances
----------
Default (RTOL_DEFAULT = 1e-3):
  Python lbftd and Matlab fnGval evaluate the same LBF spline but through
  different code paths.  First-order quantities (G, rho) agree to ~1e-15;
  second-order derivatives (alpha, Ks, Cv, vel) can differ by up to ~1e-4.
  1e-3 gives a 10× margin over the worst observed discrepancy.

Skipped fields
--------------
input_* / _fieldnames:
  Bookkeeping fields added by the reference generator.

If reference_getProp.mat is absent the whole module is skipped with a
clear message telling the user to run the Matlab generator first.
"""

import os
import warnings
import unittest as ut

import numpy as np
from scipy.io import loadmat

import seafreeze.seafreeze as sf


HERE    = os.path.dirname(os.path.abspath(__file__))
REF_PATH = os.path.normpath(os.path.join(
    HERE, '..', '..', '..', 'Matlab', 'test', 'reference_getProp.mat'))

# Properties always excluded from the numerical comparison.
_SKIP_FIELDS = frozenset({
    'input_P', 'input_T', 'input_m', 'input_type', 'input_material',
})

# Relative tolerance for all spline-derived properties.
# lbftd and Matlab fnGval agree to ~1e-4 for higher-order derivatives;
# 1e-3 gives a comfortable margin.
RTOL_DEFAULT = 1e-3

# Per-property overrides.  Stitched blend-zone second-order quantities (Js,
# gamma_Gruneisen) are assembled from two independent splines and can differ
# from Matlab by up to ~1.3e-3 — still well within physical accuracy.
RTOL_PER_PROP = {
    'Js':              2e-3,
    'gamma_Gruneisen': 2e-3,
}


def _build_ptm(case, input_type):
    """Reconstruct the Python PTm input from the stored reference arrays."""
    P = np.asarray(case.input_P, dtype=float).ravel()
    T = np.asarray(case.input_T, dtype=float).ravel()
    has_m = not (np.isscalar(case.input_m) and np.isnan(case.input_m))

    if input_type == 'scatter':
        n = P.size
        if has_m:
            m = np.asarray(case.input_m, dtype=float).ravel()
            PTm = np.empty((n,), dtype=object)
            for i in range(n):
                PTm[i] = (P[i], T[i], m[i])
        else:
            PTm = np.empty((n,), dtype=object)
            for i in range(n):
                PTm[i] = (P[i], T[i])
    else:  # grid
        if has_m:
            m = np.asarray(case.input_m, dtype=float).ravel()
            PTm = np.array([P, T, m], dtype=object)
        else:
            PTm = np.array([P, T], dtype=object)

    return PTm


def _numeric_fields(case):
    """Yield (name, array) for each numeric property field in the case struct."""
    skip = _SKIP_FIELDS
    for name in vars(case):
        # Skip scipy internal attrs (e.g. _fieldnames), input bookkeeping, and
        # any mode-specific exclusions.
        if name.startswith('_') or name.startswith('input_') or name in skip:
            continue
        val = getattr(case, name)
        try:
            arr = np.asarray(val, dtype=float)
        except (ValueError, TypeError):
            continue
        if arr.dtype.kind == 'f' and arr.size > 0:
            yield name, arr


def _compare_case(case_name, case):
    """Run getProp and compare every numeric field. Returns a dict of results."""
    input_type = str(case.input_type).strip()
    material   = str(case.input_material).strip()

    PTm = _build_ptm(case, input_type)

    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        out = sf.getProp(PTm, material)

    results = {}
    for prop, ref_arr in _numeric_fields(case):
        if not hasattr(out, prop):
            results[prop] = {'status': 'missing_in_python', 'max_relerr': None}
            continue

        py_arr = np.asarray(getattr(out, prop), dtype=float)
        # Squeeze singleton dims (loadmat may leave trailing 1s).
        ref_squeezed = ref_arr.squeeze()
        py_squeezed  = py_arr.squeeze()

        if ref_squeezed.shape != py_squeezed.shape:
            # Python may store echo/derived props in compact broadcast form
            # (e.g. m as (nm,) or (1,1,nm)) while Matlab expands to full grid.
            # Try broadcasting the smaller Python array to the Matlab shape.
            try:
                py_broadcast = np.broadcast_to(py_squeezed, ref_squeezed.shape)
            except ValueError:
                results[prop] = {
                    'status': 'shape_mismatch',
                    'ref_shape': ref_squeezed.shape,
                    'py_shape':  py_squeezed.shape,
                    'max_relerr': None,
                }
                continue
            denom  = np.abs(ref_squeezed) + 1e-300
            relerr = np.abs(py_broadcast - ref_squeezed) / denom
            max_relerr = float(np.nanmax(relerr))
            results[prop] = {'status': 'ok_broadcast', 'max_relerr': max_relerr}
            continue

        # Same shape — direct comparison.
        denom = np.abs(ref_squeezed) + 1e-300
        relerr = np.abs(py_squeezed - ref_squeezed) / denom
        max_relerr = float(np.nanmax(relerr))
        results[prop] = {'status': 'ok', 'max_relerr': max_relerr}

    return results


class TestGetPropVsMatlab(ut.TestCase):
    @classmethod
    def setUpClass(cls):
        if not os.path.exists(REF_PATH):
            raise ut.SkipTest(
                f"Reference file not found:\n  {REF_PATH}\n"
                "Run Matlab/test/gen_getProp_reference.m first.")
        cls.ref = loadmat(REF_PATH, squeeze_me=True, struct_as_record=False)

    # ------------------------------------------------------------------
    # One test method per case so failures are isolated
    # ------------------------------------------------------------------
    def _run_case(self, case_name):
        case    = self.ref[case_name]
        results = _compare_case(case_name, case)
        for prop, info in results.items():
            with self.subTest(prop=prop):
                if info['status'] == 'missing_in_python':
                    self.fail(f"{case_name}/{prop}: present in Matlab but missing in Python output")
                elif info['status'] == 'shape_mismatch':
                    self.fail(
                        f"{case_name}/{prop}: shape mismatch — "
                        f"ref={info['ref_shape']} py={info['py_shape']}")
                else:
                    tol = RTOL_PER_PROP.get(prop, RTOL_DEFAULT)
                    self.assertLessEqual(
                        info['max_relerr'], tol,
                        f"{case_name}/{prop}: max rel-err {info['max_relerr']:.3e} "
                        f"exceeds tolerance {tol:.1e}")

    def test_VI_scatter(self):      self._run_case('VI_scatter')
    def test_VI_grid(self):         self._run_case('VI_grid')
    def test_Ih_scatter(self):      self._run_case('Ih_scatter')
    def test_water1_scatter(self):  self._run_case('water1_scatter')
    def test_water1_grid(self):     self._run_case('water1_grid')
    def test_NaClaq_scatter(self):          self._run_case('NaClaq_scatter')
    def test_NaClaq_grid(self):             self._run_case('NaClaq_grid')
    def test_NaClaq_stitch_scatter(self):   self._run_case('NaClaq_stitch_scatter')
    def test_NaClaq_stitch_grid(self):      self._run_case('NaClaq_stitch_grid')


if __name__ == '__main__':
    ut.main()
