"""Cross-validation: Python phase_lines vs MATLAB SF_PhaseLines.

Loads Matlab/test/reference_phaselines.mat (generated by
gen_phaselines_reference.m) and runs the Python phase_lines on the same
dense T grid (0.005 K spacing). Asserts max |Delta T| < 0.01 K between
the two implementations.

Run from this directory (Python/seafreeze/test/):
    python -m unittest test_phaselines_vs_matlab.py

Tolerance: 0.01 K. With dT=0.005 K the contour extraction's
linear-interpolation error in T is well below this; any larger discrepancy
indicates a real difference between the two evaluators.
"""
import os
import unittest as ut
import warnings

import numpy as np
from scipy.io import loadmat
import matplotlib
matplotlib.use('Agg')

from seafreeze.phaselines import phase_lines, phase_range


HERE = os.path.dirname(os.path.abspath(__file__))
REF_PATH = os.path.normpath(os.path.join(
    HERE, '..', '..', '..', 'Matlab', 'test', 'reference_phaselines.mat'))

T_TOL = 0.01    # K
STABLE_FRAC_TOL = 0.05   # 5 percent


def _max_dT(P_a, T_a, P_b, T_b):
    """Maximum |Delta T| between two curves.

    For each point in curve A, finds the nearest point in curve B by
    Euclidean (P, T) distance after rescaling P so its range matches T's.
    Returns max |T_a - T_nearest_b|. Robust to multi-valued (in P) curves.
    """
    P_a = np.asarray(P_a, dtype=float).ravel()
    T_a = np.asarray(T_a, dtype=float).ravel()
    P_b = np.asarray(P_b, dtype=float).ravel()
    T_b = np.asarray(T_b, dtype=float).ravel()
    if P_a.size == 0 or P_b.size == 0:
        return np.inf
    # Scale P to T's typical magnitude so distance is dimensionally balanced.
    P_span = max(P_a.max() - P_a.min(), P_b.max() - P_b.min(), 1.0)
    T_span = max(T_a.max() - T_a.min(), T_b.max() - T_b.min(), 1.0)
    s = T_span / P_span
    dT_max = 0.0
    for Pa, Ta in zip(P_a, T_a):
        d2 = ((P_b - Pa) * s) ** 2 + (T_b - Ta) ** 2
        j = int(np.argmin(d2))
        dT_max = max(dT_max, abs(Ta - T_b[j]))
    return dT_max


def _compare_one(case_name, case):
    P_ref = np.asarray(case.P, dtype=float).ravel()
    T_ref = np.asarray(case.T, dtype=float).ravel()
    stable_ref = np.asarray(case.stable, dtype=bool).ravel()
    matA = str(case.matA)
    matB = str(case.matB)
    m_val = float(case.m) if not np.isnan(case.m) else None
    dT = float(case.dT)

    # Build the *same* T grid used by the Matlab reference (spline-domain
    # intersection at the recorded dT), so contour extraction error from
    # linear interpolation matches between the two implementations.
    rA = phase_range(matA)
    rB = phase_range(matB)
    Tlo = max(rA.T[0], rB.T[0], 1.0)
    Thi = min(rA.T[1], rB.T[1])
    T_grid = np.arange(Tlo, Thi + dT / 2.0, dT)

    if m_val is not None:
        r = phase_lines(matA, matB, m=m_val, T=T_grid)
    else:
        r = phase_lines(matA, matB, T=T_grid)

    P_py = np.asarray(r.P, dtype=float).ravel()
    T_py = np.asarray(r.T, dtype=float).ravel()
    stable_py = np.asarray(r.stable, dtype=bool).ravel()

    dT_max = _max_dT(P_ref, T_ref, P_py, T_py)

    frac_ref = stable_ref.mean() if stable_ref.size else 0.0
    frac_py  = stable_py.mean()  if stable_py.size  else 0.0
    frac_diff = abs(frac_py - frac_ref)

    return {
        'name': case_name,
        'matA': matA, 'matB': matB, 'm': m_val,
        'n_ref': P_ref.size, 'n_py': P_py.size,
        'dT_max': dT_max,
        'frac_ref': frac_ref, 'frac_py': frac_py,
        'frac_diff': frac_diff,
    }


class TestPhaseLinesVsMatlab(ut.TestCase):
    @classmethod
    def setUpClass(cls):
        # Fail-fast skip if reference is missing
        if not os.path.exists(REF_PATH):
            raise ut.SkipTest(
                f"Reference file not found: {REF_PATH}\n"
                f"Run Matlab/test/gen_phaselines_reference.m first.")
        cls.ref = loadmat(REF_PATH, squeeze_me=True, struct_as_record=False)

    def _run_case(self, case_name):
        case = self.ref[case_name]
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            res = _compare_one(case_name, case)
        msg = (f"{case_name}: nref={res['n_ref']} npy={res['n_py']} "
               f"max|dT|={res['dT_max']:.4g} K  "
               f"stable_frac ref={res['frac_ref']:.3f} py={res['frac_py']:.3f}")
        self.assertLess(res['dT_max'], T_TOL,
                        f"{msg} -- exceeds T tolerance {T_TOL} K")
        self.assertLess(res['frac_diff'], STABLE_FRAC_TOL,
                        f"{msg} -- stable fraction differs by "
                        f">{STABLE_FRAC_TOL}")

    # Pure-water pairs (one method per pair so failures are isolated)
    def test_Ih_water1(self):    self._run_case('Ih_water1')
    def test_Ih_II(self):        self._run_case('Ih_II')
    def test_Ih_III(self):       self._run_case('Ih_III')
    def test_II_III(self):       self._run_case('II_III')
    def test_II_V(self):         self._run_case('II_V')
    def test_II_VI(self):        self._run_case('II_VI')
    def test_II_water1(self):    self._run_case('II_water1')
    def test_III_V(self):        self._run_case('III_V')
    def test_III_water1(self):   self._run_case('III_water1')
    def test_V_water1(self):     self._run_case('V_water1')
    def test_V_VI(self):         self._run_case('V_VI')
    def test_VI_water1(self):    self._run_case('VI_water1')

    # NaClaq pairs
    def test_Ih_NaClaq_m0p5(self):  self._run_case('Ih_NaClaq_m0p5')
    def test_Ih_NaClaq_m2(self):    self._run_case('Ih_NaClaq_m2')
    def test_III_NaClaq_m0p5(self): self._run_case('III_NaClaq_m0p5')
    def test_III_NaClaq_m2(self):   self._run_case('III_NaClaq_m2')
    def test_V_NaClaq_m0p5(self):   self._run_case('V_NaClaq_m0p5')
    def test_V_NaClaq_m2(self):     self._run_case('V_NaClaq_m2')


if __name__ == '__main__':
    ut.main()
